In [16]:
from tensorflow.keras.preprocessing.text import one_hot

In [2]:
### sentences
sent=[  'the glass of milk',
     'the glass of juice',
     'the cup of tea',
    'I am a good boy',
     'I am a good developer',
     'understand the meaning of words',
     'your videos are good',]

In [17]:
sent

['the glass of milk',
 'the glass of juice',
 'the cup of tea',
 'I am a good boy',
 'I am a good developer',
 'understand the meaning of words',
 'your videos are good']

In [18]:
## Define the vocabulary size
voc_size=10000

In [19]:
sent

['the glass of milk',
 'the glass of juice',
 'the cup of tea',
 'I am a good boy',
 'I am a good developer',
 'understand the meaning of words',
 'your videos are good']

In [20]:
### One Hot Representation
one_hot_repr=[one_hot(words,voc_size)for words in sent]
one_hot_repr

[[2255, 1832, 1947, 7808],
 [2255, 1832, 1947, 1142],
 [2255, 6412, 1947, 4963],
 [7966, 6690, 8416, 1646, 242],
 [7966, 6690, 8416, 1646, 8077],
 [7875, 2255, 584, 1947, 8662],
 [6212, 5090, 1099, 1646]]

In [1]:
## word Embedding Representation

from tensorflow.keras.layers import Embedding
#from tensorflow.keras.processing.sequence import pad_sequences
from tensorflow.keras.utils import pad_sequences
from tensorflow.keras.models import Sequential

In [22]:
import numpy as np

In [23]:
sent_length=8
embedded_docs=pad_sequences(one_hot_repr,padding='pre',maxlen=sent_length)
print(embedded_docs)

[[   0    0    0    0 2255 1832 1947 7808]
 [   0    0    0    0 2255 1832 1947 1142]
 [   0    0    0    0 2255 6412 1947 4963]
 [   0    0    0 7966 6690 8416 1646  242]
 [   0    0    0 7966 6690 8416 1646 8077]
 [   0    0    0 7875 2255  584 1947 8662]
 [   0    0    0    0 6212 5090 1099 1646]]


In [24]:
## feature representation
dim=10

In [11]:
model=Sequential()
model.add(Embedding(voc_size,dim,input_length=sent_length))
model.compile('adam','mse')

In [25]:
model.summary()

Model: "sequential"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 embedding (Embedding)       (None, 8, 10)             100000    
                                                                 
Total params: 100000 (390.62 KB)
Trainable params: 100000 (390.62 KB)
Non-trainable params: 0 (0.00 Byte)
_________________________________________________________________


In [26]:
model.predict(embedded_docs)

1/1 [==============================] - 0s 48ms/step


array([[[-2.48733405e-02, -3.28700319e-02, -4.58130352e-02,
         -4.79133017e-02,  1.63968690e-02, -4.64270003e-02,
         -3.00733931e-02, -4.72835302e-02, -1.14021525e-02,
          1.60073303e-02],
        [-2.48733405e-02, -3.28700319e-02, -4.58130352e-02,
         -4.79133017e-02,  1.63968690e-02, -4.64270003e-02,
         -3.00733931e-02, -4.72835302e-02, -1.14021525e-02,
          1.60073303e-02],
        [-2.48733405e-02, -3.28700319e-02, -4.58130352e-02,
         -4.79133017e-02,  1.63968690e-02, -4.64270003e-02,
         -3.00733931e-02, -4.72835302e-02, -1.14021525e-02,
          1.60073303e-02],
        [-2.48733405e-02, -3.28700319e-02, -4.58130352e-02,
         -4.79133017e-02,  1.63968690e-02, -4.64270003e-02,
         -3.00733931e-02, -4.72835302e-02, -1.14021525e-02,
          1.60073303e-02],
        [-3.50045674e-02, -1.08880401e-02,  2.00545527e-02,
          2.75684483e-02,  1.77351125e-02, -3.37945372e-02,
          3.33614461e-02, -3.60952988e-02,  3.456851

In [27]:
embedded_docs[0]

array([   0,    0,    0,    0, 2255, 1832, 1947, 7808])

In [28]:
model.predict(embedded_docs[0])

1/1 [==============================] - 0s 26ms/step


array([[-0.02487334, -0.03287003, -0.04581304, -0.0479133 ,  0.01639687,
        -0.046427  , -0.03007339, -0.04728353, -0.01140215,  0.01600733],
       [-0.02487334, -0.03287003, -0.04581304, -0.0479133 ,  0.01639687,
        -0.046427  , -0.03007339, -0.04728353, -0.01140215,  0.01600733],
       [-0.02487334, -0.03287003, -0.04581304, -0.0479133 ,  0.01639687,
        -0.046427  , -0.03007339, -0.04728353, -0.01140215,  0.01600733],
       [-0.02487334, -0.03287003, -0.04581304, -0.0479133 ,  0.01639687,
        -0.046427  , -0.03007339, -0.04728353, -0.01140215,  0.01600733],
       [-0.03500457, -0.01088804,  0.02005455,  0.02756845,  0.01773511,
        -0.03379454,  0.03336145, -0.0360953 ,  0.03456851,  0.00566745],
       [ 0.03045399, -0.03697472,  0.04576594, -0.04472624,  0.02741272,
         0.0357053 ,  0.01350129, -0.00250307,  0.01786368, -0.03904347],
       [-0.00914966, -0.02020043, -0.03694385,  0.03663244, -0.04161234,
        -0.01140701,  0.03033885,  0.02973945